apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-test.fullname" . }}
  labels:
    {{- include "helm-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-test.selectorLabels" . | nindent 4 }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm-test.fullname" . }}-redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm-test.fullname" . }}-redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave

---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm-test.fullname" . }}-guestbook
  labels:
    app: guestbook
    branch: master 
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
